-- ROTANDARO / SUPABASE
-- Execute este SQL no SQL Editor do seu projeto Supabase.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text,
  created_at timestamptz not null default now()
);

create table if not exists public.contributions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  church text not null default 'Igreja Local',
  income numeric(14,2) not null default 0,
  tithe_percent numeric(6,2) not null default 0,
  first_percent numeric(6,2) not null default 0,
  tithe numeric(14,2) not null default 0,
  first numeric(14,2) not null default 0,
  donation_percent numeric(6,2) not null default 2.5,
  donation_institution text not null default 'Instituição',
  donation numeric(14,2) not null default 0,
  total numeric(14,2) not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists contributions_user_id_idx
  on public.contributions(user_id);

alter table public.profiles enable row level security;
alter table public.contributions enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles for select
to authenticated
using (id = auth.uid());

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles for insert
to authenticated
with check (id = auth.uid());

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists "contributions_select_own" on public.contributions;
create policy "contributions_select_own"
on public.contributions for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "contributions_insert_own" on public.contributions;
create policy "contributions_insert_own"
on public.contributions for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "contributions_update_own" on public.contributions;
create policy "contributions_update_own"
on public.contributions for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "contributions_delete_own" on public.contributions;
create policy "contributions_delete_own"
on public.contributions for delete
to authenticated
using (user_id = auth.uid());

-- Cria/atualiza automaticamente o perfil quando uma conta é criada.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1))
  )
  on conflict (id) do update
    set username = excluded.username;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Opcional: se você quiser permitir cadastro sem confirmação de e-mail,
-- no painel Supabase vá em Authentication > Providers > Email
-- e desative "Confirm email".


-- Atualização para instalações existentes:
alter table public.contributions add column if not exists donation_percent numeric(6,2) not null default 2.5;
alter table public.contributions add column if not exists donation_institution text not null default 'Instituição';
alter table public.contributions add column if not exists donation numeric(14,2) not null default 0;
